<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="LibreOffice 4.1.6.2 (Linux)">
	<META NAME="AUTHOR" CONTENT="Amey Jadhav">
	<META NAME="CREATED" CONTENT="20200709;151900000000000">
	<META NAME="CHANGEDBY" CONTENT="Windows User">
	<META NAME="CHANGED" CONTENT="20200903;152500000000000">
	<META NAME="AppVersion" CONTENT="15.0000">
	<META NAME="DocSecurity" CONTENT="0">
	<META NAME="HyperlinksChanged" CONTENT="false">
	<META NAME="LinksUpToDate" CONTENT="false">
	<META NAME="ScaleCrop" CONTENT="false">
	<META NAME="ShareDoc" CONTENT="false">
	<STYLE TYPE="text/css">
	</STYLE>
</HEAD>
<BODY LANG="en-AU" DIR="LTR">
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in">“<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માનવ</FONT>
<FONT FACE="Nirmala UI">કલ્યાણ</FONT> <FONT FACE="Nirmala UI">ટ્રસ્ટ</FONT>”</SPAN></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>શ્રી</B></FONT><B>
</B><FONT FACE="Nirmala UI"><B>મહેશભાઈ</B></FONT><B>
</B><FONT FACE="Nirmala UI"><B>સવજીભાઈ</B></FONT><B>
</B><FONT FACE="Nirmala UI"><B>કોઠારી</B></FONT><B> </B><FONT FACE="Nirmala UI"><B>મુક</B></FONT><B>
</B></SPAN></FONT><B>- </B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>બધીર</B></FONT><B>
</B><FONT FACE="Nirmala UI"><B>માધ્યમિક અને
અચ્છ્તર માધ્યમિક શાળા</B></FONT></SPAN></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>શ્રી
સી</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>.
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>એલ</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>.
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પારેખ
“મમતા મંદિર” મહેશભાઈ કોઠારી
માર્ગ</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>,
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વિજલપોર</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>,</B></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>તા</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>.
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>જલાલપોર</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>,
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>જિ</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>.
</B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નવસારી
</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>- 396450</B></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>બોનાફાઇડ
પ્રમાણપત્ર</B></FONT></SPAN></FONT></P>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.11in"><A NAME="_GoBack"></A><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જા</FONT></SPAN></FONT>.
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નંબર</FONT></SPAN></FONT><B>.		</B>						<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">તારીખ</FONT></SPAN></FONT>:
<B>$data.joiningDate$</B></P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.11in"><FONT FACE="Nirmala UI, serif">					</FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">આથી</FONT>
<FONT FACE="Nirmala UI">પ્રમાનપત્ર</FONT> <FONT FACE="Nirmala UI">આપ્વામા</FONT>
<FONT FACE="Nirmala UI">આવે</FONT> <FONT FACE="Nirmala UI">છે</FONT>
<FONT FACE="Nirmala UI">કે</FONT></SPAN></FONT>, <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કુમાર</FONT>
</SPAN></FONT>/ <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કુમારી</FONT>
<FONT FACE="Nirmala UI">ધોરણ  </FONT>  </SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>$data.empName$</B></FONT><FONT FACE="Nirmala UI, serif">
</FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માં
</FONT> <FONT FACE="Nirmala UI">અમારી</FONT> <FONT FACE="Nirmala UI">શાળા</FONT>
<FONT FACE="Nirmala UI">મા</FONT> <FONT FACE="Nirmala UI">શૈક્ષણીક</FONT>
<FONT FACE="Nirmala UI">વર્ષ</FONT> </SPAN></FONT><B>$standard$</B>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માં
</FONT> <FONT FACE="Nirmala UI">અભ્યાસ</FONT> <FONT FACE="Nirmala UI">કરે</FONT>
<FONT FACE="Nirmala UI">છે </FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>$year$</B></FONT>
. <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">અમારી</FONT>
<FONT FACE="Nirmala UI">શાળાના</FONT> <FONT FACE="Nirmala UI">જેનેરલ</FONT>
<FONT FACE="Nirmala UI">રેજિસ્ટર</FONT> <FONT FACE="Nirmala UI">પ્રમાણે</FONT>
<FONT FACE="Nirmala UI">તેની</FONT> <FONT FACE="Nirmala UI">જન્મ</FONT>
<FONT FACE="Nirmala UI">તારીખ</FONT> </SPAN></FONT><B>$dob$</B>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">અને</FONT>
<FONT FACE="Nirmala UI">તેની</FONT> <FONT FACE="Nirmala UI">જાતિ</FONT></SPAN></FONT>,
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">પેટાજ્ઞાતિ</FONT>
</SPAN></FONT><B>$cast$</B> <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">છે</FONT></SPAN></FONT>.
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">તેનો</FONT>
<FONT FACE="Nirmala UI">જેનેરલ</FONT> <FONT FACE="Nirmala UI">રેજિસ્ટર</FONT>
<FONT FACE="Nirmala UI">નંબર</FONT>  </SPAN></FONT><B>$registrationnumber$
</B> <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">છે</FONT></SPAN></FONT>.</P>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.11in"><FONT FACE="Nirmala UI, serif">					</FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">મારી</FONT>
<FONT FACE="Nirmala UI">જાણ</FONT> <FONT FACE="Nirmala UI">મુજબ</FONT>
<FONT FACE="Nirmala UI">તેની</FONT> <FONT FACE="Nirmala UI">ચાલચલગત</FONT>
<FONT FACE="Nirmala UI">તથા</FONT> <FONT FACE="Nirmala UI">વ્યવહાર</FONT>
<FONT FACE="Nirmala UI">સારા</FONT> <FONT FACE="Nirmala UI">છે</FONT></SPAN></FONT>.
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઉપરોક્ત</FONT>
<FONT FACE="Nirmala UI">વિગત</FONT> <FONT FACE="Nirmala UI">શાળાના</FONT>
<FONT FACE="Nirmala UI">જેનેરલ</FONT> <FONT FACE="Nirmala UI">રેજિસ્ટરના</FONT>
<FONT FACE="Nirmala UI">આધારે</FONT> <FONT FACE="Nirmala UI">નોંધવામાં</FONT>
<FONT FACE="Nirmala UI">આવે</FONT> <FONT FACE="Nirmala UI">છે</FONT></SPAN></FONT>.</P>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P ALIGN=JUSTIFY STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P ALIGN=RIGHT STYLE="margin-bottom: 0.11in">						<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">આચાર્ય</FONT></SPAN></FONT></P>
<P ALIGN=CENTER STYLE="margin-bottom: 0.11in">                       
                           <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">શ્રી</FONT>
<FONT FACE="Nirmala UI">મ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કોઠારી</FONT>
<FONT FACE="Nirmala UI">મુક</FONT> </SPAN></FONT>- <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">બધીર</FONT>
<FONT FACE="Nirmala UI">માધ્યમિક અને અચ્છ્તર
માધ્યમિક શાળા</FONT></SPAN></FONT></P>
<P ALIGN=RIGHT STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વિજલપોરે</FONT></SPAN></FONT>,
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નવસારી</FONT></SPAN></FONT></P>
<P ALIGN=RIGHT STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P ALIGN=RIGHT STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><B>Results:</B></P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Nirmala UI, serif">		</FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">શ્રી</FONT>
<FONT FACE="Nirmala UI">મ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કોઠારી</FONT>
<FONT FACE="Nirmala UI">મુક</FONT> </SPAN></FONT>- <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">બધીર</FONT>
<FONT FACE="Nirmala UI">માધ્યમિક અને અચ્છ્તર
માધ્યમિક શાળા</FONT> </SPAN></FONT>
</P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નામ</FONT></SPAN></FONT>:
________</P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ધોરણ</FONT></SPAN></FONT>:
8-9-10                 	                        <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વર્ષ</FONT></SPAN></FONT>:
20__ - 20__                                                <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">રોલ</FONT>
<FONT FACE="Nirmala UI">નો</FONT></SPAN></FONT>.: ______</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<TABLE WIDTH=565 CELLPADDING=7 CELLSPACING=0>
	<COL WIDTH=96>
	<COL WIDTH=32>
	<COL WIDTH=4358>
	<COL WIDTH=4357>
	<COL WIDTH=23>
	<COL WIDTH=4357>
	<COL WIDTH=30>
	<COL WIDTH=30>
	<COL WIDTH=129>
	<COL WIDTH=72>
	<COL WIDTH=4359>
	<COL WIDTH=28>
	<TR VALIGN=TOP>
		<TD ROWSPAN=2 WIDTH=96 HEIGHT=16 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વિષય</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=4 WIDTH=74 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પ્રથમ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=76 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>દ્વિતીય</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=129 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P ALIGN=JUSTIFY STYLE="margin-left: 0.33in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નોટબુક</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>સુબમિસ્સીઓન</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=72 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>સુબજેક્ટ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>એકટીવીટી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>કુલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD COLSPAN=2 WIDTH=35 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(80)</B></P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(80)</B></P>
		</TD>
		<TD WIDTH=30 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD WIDTH=129 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD WIDTH=72 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(20)</B></P>
		</TD>
	</TR>
	<TR>
		<TD COLSPAN=12 WIDTH=549 HEIGHT=18 VALIGN=TOP STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P ALIGN=CENTER><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>જૂથ</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>1</B></FONT><B>
			</B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ફરજીયાત</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>વિષયો</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=15 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.5in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ગુજરાતી</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=16 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઇંગલિશ</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=18 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સામાજિક</FONT>
			<FONT FACE="Nirmala UI">વિજ્ઞાન</FONT>  </SPAN></FONT>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=18 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ગણિત</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=21 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વિજ્ઞાન</FONT>
			<FONT FACE="Nirmala UI">અને</FONT> <FONT FACE="Nirmala UI">ટચનોલોજી</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=17 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કુલ</FONT>
			<FONT FACE="Nirmala UI">ગુણ</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=25 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=17 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ટકા</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=5 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=15 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">રેન્ક</FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=5 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=12 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">પરિણામ</FONT>
			</SPAN></FONT>(<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">પાસ</FONT></SPAN></FONT>/<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નાપાસ</FONT></SPAN></FONT>)</P>
		</TD>
		<TD COLSPAN=5 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=76 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD COLSPAN=12 WIDTH=549 HEIGHT=12 VALIGN=TOP STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P ALIGN=CENTER><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>જૂથ</B></FONT><B>
			</B></SPAN></FONT><B>2 </B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વૈકલ્પિક</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>વિષયો</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD ROWSPAN=2 WIDTH=96 HEIGHT=47 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વિષય</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=4 WIDTH=74 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પ્રથમ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=76 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>દ્વિતીય</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=129 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P ALIGN=JUSTIFY STYLE="margin-left: 0.33in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નોટબુક</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>સુબમિસ્સીઓન</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=72 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>સુબજેક્ટ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>એકટીવીટી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>કુલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(100)</B></P>
		</TD>
		<TD COLSPAN=3 WIDTH=28 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(100)</B></P>
		</TD>
		<TD WIDTH=30 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD WIDTH=129 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P ALIGN=JUSTIFY STYLE="margin-left: 0.33in"><B>(5)</B></P>
		</TD>
		<TD WIDTH=72 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(5)</B></P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 BGCOLOR="#ffffff" STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><B>(20)</B></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=20 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કમ્પ્યુટર</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=72 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=96 HEIGHT=19 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ચિત્રકામ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=28 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=129 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD WIDTH=72 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=32 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.05in"><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વાલીની</FONT>
<FONT FACE="Nirmala UI">સહી</FONT>                             
                 <FONT FACE="Nirmala UI">વર્ગ</FONT> <FONT FACE="Nirmala UI">શિક્ષકની</FONT>
<FONT FACE="Nirmala UI">સહી</FONT>                             
             <FONT FACE="Nirmala UI">આચાર્યની</FONT>
<FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<TABLE WIDTH=601 CELLPADDING=7 CELLSPACING=0>
	<COL WIDTH=85>
	<COL WIDTH=86>
	<COL WIDTH=86>
	<COL WIDTH=86>
	<COL WIDTH=86>
	<COL WIDTH=85>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માસ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કાર્ય</FONT>
			<FONT FACE="Nirmala UI">દિવસ</FONT> </SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">હાજર</FONT>
			<FONT FACE="Nirmala UI">દિવસ</FONT> </SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વર્ગ</FONT>
			<FONT FACE="Nirmala UI">શિક્ષકની</FONT> <FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વાલીની</FONT>
			<FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">આચાર્યની</FONT>
			<FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જૂન</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જુલાઈ</FONT>
			</SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઓગસ્ટ</FONT>
			</SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સપ્ટેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઓક્ટોબર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નવેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ડિસેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જાન્યુઆરી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ફેબ્રુઆરી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માર્ચ</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">એપ્રિલ</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">મે</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=86 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=85 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><B>Results:</B></P>
<P STYLE="margin-bottom: 0.11in">                            <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">શ્રી</FONT>
<FONT FACE="Nirmala UI">મ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સ</FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif">.</FONT>
<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કોઠારી</FONT>
<FONT FACE="Nirmala UI">મુક</FONT> </SPAN></FONT>- <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">બધીર</FONT>
<FONT FACE="Nirmala UI">માધ્યમિક અને અચ્છ્તર
માધ્યમિક શાળા</FONT> </SPAN></FONT>
</P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નામ</FONT></SPAN></FONT>:
________</P>
<P STYLE="margin-bottom: 0.11in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ધોરણ</FONT></SPAN></FONT>:
11-12                 	                        <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વર્ષ</FONT></SPAN></FONT>:
20__ - 20__                                                <FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">રોલ</FONT>
<FONT FACE="Nirmala UI">નો</FONT></SPAN></FONT>.: ______</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<TABLE WIDTH=560 CELLPADDING=7 CELLSPACING=0>
	<COL WIDTH=77>
	<COL WIDTH=27>
	<COL WIDTH=79>
	<COL WIDTH=51>
	<COL WIDTH=14>
	<COL WIDTH=27>
	<COL WIDTH=45>
	<COL WIDTH=5>
	<COL WIDTH=28>
	<COL WIDTH=27>
	<COL WIDTH=27>
	<TR VALIGN=TOP>
		<TD ROWSPAN=2 WIDTH=77 HEIGHT=24 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વિષય</B></FONT></SPAN></FONT></P>
		</TD>
		<TD ROWSPAN=2 WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પ્રથમ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT><B> </B></SPAN></FONT>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>દ્વિતીય</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=4 WIDTH=146 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વાર્ષિક</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>કસોટી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નોંધ</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>મેળવેલ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>કોન્ડોન</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>કૃપા</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ગુણ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-right: -0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=18 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ગુજરાતી</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=16 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઇંગલિશ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=20 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">મનોવિજ્ઞાન</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=22 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">તત્વજ્ઞાન</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=18 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સ</FONT></SPAN></FONT>.
			<FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">શાસ્ત્ર</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=15 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ભૂગોળ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=20 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કમ્પ્યુટર</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>50</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=26 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P>100</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કુલ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=45 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=46 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=27 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD COLSPAN=2 WIDTH=118 HEIGHT=30 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પરિણામ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પાસ</B></FONT></SPAN></FONT><B>/</B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નાપાસ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=2 WIDTH=79 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પાસ</B></FONT></SPAN></FONT><B>/</B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નાપાસ</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=6 WIDTH=228 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>પાસ
			</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>/ </B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ઉપર
			</B></FONT></SPAN></FONT><FONT FACE="Nirmala UI, serif"><B>/ </B></FONT><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>નાપાસ</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD COLSPAN=11 WIDTH=544 HEIGHT=30 VALIGN=TOP STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ઉતીર્ણ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>ક્રમ……</B></FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=35 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વર્ગ</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>શી</B></FONT></SPAN></FONT><B>.
			</B><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>ની</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>સહી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=184 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=4 WIDTH=133 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=109 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>વાલીની</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>સહી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=184 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=4 WIDTH=133 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=109 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=77 HEIGHT=35 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI"><B>આચાર્યની</B></FONT><B>
			</B><FONT FACE="Nirmala UI"><B>સહી</B></FONT></SPAN></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=184 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=4 WIDTH=133 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=109 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<TABLE WIDTH=601 CELLPADDING=7 CELLSPACING=0>
	<COL WIDTH=60>
	<COL WIDTH=34>
	<COL WIDTH=34>
	<COL WIDTH=48>
	<COL WIDTH=69>
	<COL WIDTH=4361>
	<COL WIDTH=31>
	<COL WIDTH=71>
	<COL WIDTH=56>
	<COL WIDTH=66>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માસ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">કૂલ</FONT>
			 <FONT FACE="Nirmala UI">દિવસ</FONT> </SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">હાજર</FONT>
			<FONT FACE="Nirmala UI">દિવસ</FONT> </SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">અભ્યાસ</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=69 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.29in; margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વર્તણુક</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=37 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-left: 0.01in; margin-bottom: 0in"><BR>
			</P>
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વિશેષ</FONT>
			<FONT FACE="Nirmala UI">નોંધ</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વર્ગ</FONT>
			<FONT FACE="Nirmala UI">શિક્ષકની સહી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">વાલીની</FONT>
			<FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">આચાર્યની</FONT>
			<FONT FACE="Nirmala UI">સહી</FONT></SPAN></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જૂન</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જુલાઈ</FONT>
			</SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઓગસ્ટ</FONT>
			</SPAN></FONT>
			</P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">સપ્ટેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ઓક્ટોબર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">નવેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ડિસેમ્બર</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">જાન્યુઆરી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">ફેબ્રુઆરી</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">માર્ચ</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P STYLE="margin-bottom: 0in"><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">એપ્રિલ</FONT></SPAN></FONT></P>
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=60 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><FONT FACE="Calibri"><SPAN LANG="ar-SA"><FONT FACE="Nirmala UI">મે</FONT></SPAN></FONT></P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=34 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=48 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD COLSPAN=2 WIDTH=75 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=31 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=71 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=56 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
		<TD WIDTH=66 STYLE="border: 1px solid #00000a; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in">
			<P><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.11in"><BR><BR>
</P>
</BODY>
</HTML>
